[SC-929] Created abstract `Distributor` contract
1inch/farming pull request #72
Opened 2023-10-24 15:42 UTC by byshape

2023-10-26 08:35 UTC, ZumZoom commented on contracts/Distributor.sol
> +    error ZeroDistributorAddress();
We can move this to interface

2023-10-26 08:41 UTC, ZumZoom requested changes

2023-10-26 08:41 UTC, ZumZoom commented on contracts/Distributor.sol
> +    error ZeroDistributorAddress();
```suggestion
```

2023-10-26 08:41 UTC, ZumZoom commented on contracts/interfaces/IDistributor.sol
> +    /**
```suggestion
    event DistributorChanged(address newDistributor);

    error NotDistributor();
    error ZeroDistributorAddress();

    /**
```

2023-10-26 11:03 UTC, ZumZoom approved these changes

2023-10-27 09:33 UTC, SevenSwen approved these changes

2023-10-27 17:32 UTC, merged